echo 'applications:' > .upsun/config.yaml
echo '    app:' >> .upsun/config.yaml
echo '        type: "nodejs:20"' >> .upsun/config.yaml
echo '' >> .upsun/config.yaml
echo 'routes:' >> .upsun/config.yaml
echo '    "https://{default}/":' >> .upsun/config.yaml
echo '        type: proxy' >> .upsun/config.yaml
echo '        to: "http://178.62.247.103:80"' >> .upsun/config.yaml
echo '    "http://{default}/":' >> .upsun/config.yaml
echo '        type: redirect' >> .upsun/config.yaml
echo '        to: "https://{default}/"' >> .upsun/config.yaml
