applications:
  app:
    type: nodejs:20
  backend:
    type: python:3.11

routes:
  https://{default}/:
    type: proxy
    to: app:3000
  https://{default}/api:
    type: proxy
    to: backend:8080
